#if !canImport(ObjectiveC)
import XCTest

extension VulkanTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VulkanTests = [
        ("testFunction", testFunction)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VulkanTests.__allTests__VulkanTests)
    ]
}
#endif
