name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linux-test-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Restore APT cache
        uses: actions/cache@v2
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt
      - name: Restore cached SPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            .build/repositories
          key: ${{ runner.os }}-spm-repos-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-repos-
      - name: Install Vulkan SDK
        run: make setup-vulkan-linux
      - name: Test
        run: make test
      - name: Build Release
        run: make build-release
