name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos-test-build-release:
    runs-on:  macos-latest
    strategy:
      matrix:
        xcode: ["13.4.1", "14.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Restore cached Homebrew dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew/vulkansdk--*
            ~/Library/Caches/Homebrew/downloads/*--vulkansdk-*
          key: ${{ runner.os }}-brew-vulkan-sdk-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: ${{ runner.os }}-brew-vulkansdk-
      - name: Restore cached SPM dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build/repositories
          key: ${{ runner.os }}-spm-repos-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-repos-
      - name: Setup Vulkan SDK
        run: make setup-vulkan-macOS
      - name: Test
        run: make test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Build Release
        run: make build-release
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
