name: Check markdown links

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
